### ISSUE TITLE
generation of bamlist

### ISSUE THREAD

**Issue by DiegoZavallo** [MikeAxtell/sRNA_Viewer#3]
Hi Mike!
I really like your new sRNA_Viewer script. It's just what I need!
however I'm having some troubles that I don´t quite understand.
First the format of the -c option: My gff file have on the chromosome column the ST4.03 version of the potato genome. Do I need to change that?  or in the -c option I write only  ch06:51874728-51876278. Or is it something else?

Ans secondly I don´t undestand this error, is it something in the bam files?

> Error in `mutate()`:
> > ! Problem while computing `<21 = Coverage - `>20``.
> > Caused by error in `` Coverage - `>20` ``:
> > ! non-numeric argument to binary operato

This is my code:

`Rscript --vanilla sRNA_Viewer -g /home/diego/Documents/INTA/sRNASeq/Stuberosum_Alotetraploides/bed_gff/PGSC_DM_V403_genes_sorted.gff.gz -c ST4.03ch06:51874728-51876278 -b /home/diego/Documents/INTA/sRNASeq/Stuberosum_Alotetraploides/ShortStack/shortStack_U/bam/bamlist.csv -p /home/diego/Documents/INTA/sRNASeq/Stuberosum_Alotetraploides/ShortStack/shortStack_U/bam/test.pdf`

> Warning messages:
> 1: package ‘ggplot2’ was built under R version 4.1.3 
> 2: package ‘tidyr’ was built under R version 4.1.3 
> 3: package ‘purrr’ was built under R version 4.1.3 
> 4: package ‘dplyr’ was built under R version 4.1.3 
> 5: package ‘stringr’ was built under R version 4.1.3 
> [main_samview] region "ST4.03ch06:51874728-51876278" specifies an invalid region or unknown reference. Continue anyway.
> samtools depth: cannot parse region "ST4.03ch06:51874728-51876278"
> samtools depth: cannot parse region "ST4.03ch06:51874728-51876278"
> samtools depth: cannot parse region "ST4.03ch06:51874728-51876278"
> samtools depth: cannot parse region "ST4.03ch06:51874728-51876278"
> samtools depth: cannot parse region "ST4.03ch06:51874728-51876278"
> samtools depth: cannot parse region "ST4.03ch06:51874728-51876278"
> Error in `mutate()`:
> ! Problem while computing `<21 = Coverage - `>20``.
> Caused by error in `` Coverage - `>20` ``:
> ! non-numeric argument to binary operator
> Backtrace:
>      ▆
>   1. ├─global sRNA_depths(bamfile, bamname, coords, NULL)
>   2. │ └─... %>% mutate(Strand = "+")
>   3. ├─dplyr::mutate(., Strand = "+")
>   4. ├─dplyr::select(...)
>   5. ├─dplyr::mutate(...)
>   6. ├─dplyr::mutate(., `23` = Coverage - `>23` - `22` - `21` - `<21`)
>   7. ├─dplyr::mutate(., `22` = Coverage - `>22` - `21` - `<21`)
>   8. ├─dplyr::mutate(., `21` = Coverage - `>21` - `<21`)
>   9. ├─dplyr::mutate(., `<21` = Coverage - `>20`)
>  10. ├─dplyr:::mutate.data.frame(., `<21` = Coverage - `>20`)
>  11. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
>  12. │   ├─base::withCallingHandlers(...)
>  13. │   └─mask$eval_all_mutate(quo)
>  14. └─base::.handleSimpleError(...)
>  15.   └─dplyr (local) h(simpleError(msg, call))
>  16.     └─rlang::abort(...)
> Warning messages:
> 1: In system(paste(left, right), intern = TRUE) :
>   running command 'samtools depth -g 16 -a -r ST4.03ch06:51874728-51876278 temp.bam' had status 1
> 2: In system(paste(left, "-l 25", right), intern = TRUE) :
>   running command 'samtools depth -g 16 -a -r ST4.03ch06:51874728-51876278 -l 25 temp.bam' had status 1
> 3: In system(paste(left, "-l 24", right), intern = TRUE) :
>   running command 'samtools depth -g 16 -a -r ST4.03ch06:51874728-51876278 -l 24 temp.bam' had status 1
> 4: In system(paste(left, "-l 23", right), intern = TRUE) :
>   running command 'samtools depth -g 16 -a -r ST4.03ch06:51874728-51876278 -l 23 temp.bam' had status 1
> 5: In system(paste(left, "-l 22", right), intern = TRUE) :
>   running command 'samtools depth -g 16 -a -r ST4.03ch06:51874728-51876278 -l 22 temp.bam' had status 1
> 6: In system(paste(left, "-l 21", right), intern = TRUE) :
>   running command 'samtools depth -g 16 -a -r ST4.03ch06:51874728-51876278 -l 21 temp.bam' had status 1
> Execution halted

Could you give me a hint?

Cheers

Diego

**Comment by DiegoZavallo** [comment]
Hi Mike, its me again.
I think I resolve the -c format but now its halted with this:

`Rscript --vanilla sRNA_Viewer -g /home/diego/Documents/INTA/sRNASeq/Stuberosum_Alotetraploides/bed_gff/PGSC_DM_V403_genes_sorted.gff.gz -c chr06:51874728-51876278 -b /home/diego/Documents/INTA/sRNASeq/Stuberosum_Alotetraploides/ShortStack/shortStack_U/bam/bamlist.csv -p /home/diego/Documents/INTA/sRNASeq/Stuberosum_Alotetraploides/ShortStack/shortStack_U/bam/test.pdf`

> 
> Warning messages:
> 1: package ‘ggplot2’ was built under R version 4.1.3 
> 2: package ‘tidyr’ was built under R version 4.1.3 
> 3: package ‘purrr’ was built under R version 4.1.3 
> 4: package ‘dplyr’ was built under R version 4.1.3 
> 5: package ‘stringr’ was built under R version 4.1.3 
> **Error: object 'Ybins' not found**
> Execution halted
> 

I read in your web page that you have to add YS tags to the bam files in order to run sRNA_viewer but I dont find the script on your github, neither the add_YS.pl nor sRNA_coverage.pl. Is it because they are integrated in sRNA_viewer?
What I am missing here?

Thanks

Diego

**Comment by MikeAxtell** [comment]
Hi Diego,

The 'YS' tags are obsoleted in this newer version of sRNA_Viewer, so that is not the problem. Those warnings you are getting indicate that various required R packages were built under a different version of R than you are using to execute. I would try a fresh install / build of R and all required packages. A new conda environment might be perfect for isolating it.

**Comment by DiegoZavallo** [comment]
Hi Mike, you are right, that wasn't the problem,
I had differences on the chromosome names between the bam files and the gff file. I re-did the tabix files and it works just fine!
Thanks a lot!
